### ISSUE TITLE
Generic error message (occasionally) on auto-backup

### ISSUE THREAD

**Issue by Niceygy** [UFO-Studios/bds-companion#6]
![image](https://github.com/UFO-Studios/bds-companion/assets/80964340/d0551f55-dc9e-425c-abca-89902ca58c01)
This error message occurs. Looks like it is when zipping.
Cannot currently be accurately replicated.

**Comment by Niceygy** [comment]
# This is a priority!

**Comment by TheAlienDoctor** [comment]
I believe this is fixed, otherwise cannot be reliably reproduced
